### ISSUE TITLE
Debatepedia data in BERT format

### ISSUE THREAD

**Issue by chulakar** [tahmedge/QR-BERTSUM-TL-for-QFAS#1]
Hi,
Thank you for making your code available!
The shell script to run `QR-BERTSUM-TL` uses the `Debatepedia` dataset in the format required by the `BERT` model. Is the `Debatepedia` data available in this format? If not, how should someone convert the dataset?

Thanks

**Comment by tahmedge** [comment]
Hi, Debatepedia dataset is not available in the required format. 

To convert the dataset, please follow step 2, 3, 4, and 5 given here: https://github.com/nlpyang/PreSumm

**Comment by TysonYu** [comment]
hi @tahmedge, I find that the Debatepedia original data format is not the same as cnn/dailymail. How to deal with this problem?

**Comment by tahmedge** [comment]
@TysonYu , I have added the script to convert Debatepedia dataset into CNN-DM format. You can find it here: https://github.com/tahmedge/QR-BERTSUM-TL-for-QFAS/tree/master/QR-BERTSUM-TL/data_fold 
Hope that helps.
